# Generated by Django 4.1.2 on 2022-10-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="PicUpload",),
    ]
